package cgfile

import (
	"github.com/onkeypress-llc/codegen/cg/cgelement"
	"github.com/onkeypress-llc/codegen/cg/cgi"
)

type FileData struct {
	// generate line comment for partially/fully generated files
	GoGenerateCommentLine *cgelement.LineComment
	// generated by line comment for fully generated files
	GeneratedFileCommentLine *cgelement.LineComment
	// header comment
	Header cgi.NodeOutputInterface
	// package of this file
	PackageName string
	// union of imports used in the file
	Imports cgi.ImportSetInterface
	// set of content in the file
	Contents []cgi.NodeOutputInterface
}
