package cgelement

const DefaultGeneratedBy = "by unspecified script;"

// Example: "Code generated by my-generator-script; DO NOT EDIT."
func NewGeneratedFileLineComment(generatedBy string) *LineComment {
	if generatedBy == "" {
		generatedBy = DefaultGeneratedBy
	}
	return NewLineComment("Code generated %s DO NOT EDIT.", generatedBy)
}
